[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nora-opt"
version = "0.1.0"
authors = [
  { name="Jinghui Yuan", email="yuanjh@mail.nwpu.edu.cn" },
  { name="JiaJun Zou", email="jiaxuanzou@stu.xjtu.edu.cn" },
  { name="Shuo Wang", email="runner21st@gmail.com" },
]
description = "Nora: Normalized Orthogonal Row Alignment optimizer for PyTorch."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
"Homepage" = "https://github.com/Yuan-Jinghui/nora-opt"